### ISSUE TITLE
Lists!

### ISSUE THREAD

**Issue by Matt2012** [mduvall/grande.js#1]
I know the whole idea is minimal but ordered and unordered lists as a plugin option would be great - and that is the only missing thing.

The way I see it is you highlight the text choose list icon and it indents the line and starts the list returning creates the new item deleting that breaks out of list.

**Comment by mduvall** [comment]
@Matt2012 Yes! This is next on the roadmap, coming down the pipeline :+1:

**Comment by mduvall** [comment]
Closed via https://github.com/mduvall/grande.js/pull/4.
