### ISSUE TITLE
Could I add align features?

### ISSUE THREAD

**Issue by madthad91** [mduvall/grande.js#11]

**Comment by mduvall** [comment]
Sounds interesting! Is this similar to word document programs for justify, left-justify, right-justify? I would definitely be up to have this on the backlog if it's something that could be cleverly implemented in the UI without being a distraction. This adds for the case to have something similar to a `grande-ui` repository to provide additional functionality.

Sidenote: Is this something Medium supports? The current roadmap is to become feature complete for what Medium has to offer and expand after that.

**Comment by y-lohse** [comment]
I don't think they do, no. I believe they want an editor that only lets the user define structure, not style; yet text justification is more a matter of style.
Haven't checked, but `execCommand` with `justifyLeft` would probably inject css, not sure if that's a good idea. I really like the grande-ui repo idea though.
