### ISSUE TITLE
Unable to install through bower.

### ISSUE THREAD

**Issue by bIgBV** [mduvall/grande.js#15]
I tried to install this through Bower but it is showing the following error : 

```
bower grande#*              not-cached git://github.com:mduvall/grande.js.git#*
bower grande#*                 resolve git://github.com:mduvall/grande.js.git#*
bower grande#*                 ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com:mduvall/grande.js.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com: Servname not supported for ai_socktype
```

I did a google search and I got this [StackOverflow](http://stackoverflow.com/questions/2871831/git-error-unable-to-look-up-xyz-com-port-none-servname-not-supported-for-a) result. 

Can you have a look, I would really like to use grande.Thanks!

**Comment by mduvall** [comment]
Sorry about that, I put in the wrong git URL. I updated this ticket here https://github.com/bower/bower/issues/120 for the Bower project to remove the current reference and I'll update the registration once that happens. Thanks for hanging tight!
