### ISSUE TITLE
Description is too awesome.

### ISSUE THREAD

**Issue by ericclemmons** [mduvall/grande.js#16]
> It's a Medium at Starbucks. Pinky ring out.

I mean, seriously.  Isn't a Medium-inspired editor _good enough??_

**Comment by mduvall** [comment]
![sunglasses](http://31.media.tumblr.com/c85013cce69eb0aebc0218119d2a18d3/tumblr_mhzr16g7891ryc8o6o1_500.gif)

**Comment by ericclemmons** [comment]
Touché.
