### ISSUE TITLE
Backspace bugs

### ISSUE THREAD

**Issue by y-lohse** [mduvall/grande.js#20]
Right now, backspaces in grande behave a bit differently than on medium. Here's a non-exhaustive list of issues I noticed:
### H1 WTF in Chrome

Carret at the start of an h1 which is preceeded by a paragraph, hit backspace; the content of the node is appended to the previous paragraph _but_ surrounded with a `<span style="font-size:2em">` (i wiish I were kidding :p)

On medium the nodes content is simply appended to the previous paragraph.
### Cancelling `li`s

On medium, when the carret is at the start of an `li` and the user presses backspaces, the `li` is turned into a `p`, regardless of the content of that `li` or the number of surrounding `li`s.

In grande the behavior differs depending on the browser. Chrome usually deletes the li and appends the content to the previous tag, regardless of what that previous tag is.
Firefox has a range of different behaviors depending on whether the `li` contains text or not, whether it's inside and `ol` or `ul` or even the `li`s position in the list.
### Deleting `hr`s

I didn't mention it in #19 but `hr` deletion will need adressing too. Chrome handles it rather fine, but Firefox and IE do very different (and non-sensical) things.

**Comment by mduvall** [comment]
I opened up several issues from this ticket https://github.com/mduvall/grande.js/issues/25, https://github.com/mduvall/grande.js/issues/24, https://github.com/mduvall/grande.js/issues/23. It will be easier if somebody would like to open a PR.

Thanks a lot for finding these!
