### ISSUE TITLE
Input blurs when trying to insert a link url via CTRL-V

### ISSUE THREAD

**Issue by jsphpl** [mduvall/grande.js#28]
The menu turns back to the normal buttons view when i press ctrl on the url input.
I'm on a linux machine if that matters. Problem occurs in both ff and chrome. Seems to work fine on Mac with the cmd key.

**Comment by y-lohse** [comment]
I'm unable to reproduce it on windows, latest chrome or firefox and from just looking at the code I see nothing suspicious :/

**Comment by mduvall** [comment]
Having the same issue reproducing, opened up a 12.04 VM in VirtualBox and couldn't repro.  Feel free to open it up again with a screencast or something if it continues to happen.

**Comment by jsphpl** [comment]
Alight, thanks anyway for the investigations!
