### ISSUE TITLE
Unable to make a heading bold in firefox

### ISSUE THREAD

**Issue by jsphpl** [mduvall/grande.js#29]
Text in a heading (tested h1-3) won't turn bold. It is possible to turn text that is already bold into a heading, but not the other way round. Occurs in firefox on both linux and mac. Works fine in chrome.
Thanks for the nice editor guys! Keep on that nice work!

**Comment by jsphpl** [comment]
And, of course, let us know in case we can help...

**Comment by mduvall** [comment]
Good catch, it looks like `execCommand` is borked here and Medium doesn't allow bold on headers through the toolbar. The same is done in the fix.

**Comment by mduvall** [comment]
Closed via https://github.com/mduvall/grande.js/pull/30.

**Comment by jsphpl** [comment]
Thanks and sorry for issuing this again!
