### ISSUE TITLE
Options init problem

### ISSUE THREAD

**Issue by netoneko** [mduvall/grande.js#45]
Please take a look at this commit: https://github.com/netoneko/grande.js/commit/93156c0f65453aa0d921390b51496121e65c538b

You set options after init has already happened which makes them essentially useless.

**Comment by mduvall** [comment]
Great catch, if you want you could make a pull request if you want to get the commit in - if not I'll add it and reference your change.

Thanks for that @netoneko!

**Comment by mduvall** [comment]
Closed via https://github.com/mduvall/grande.js/pull/46.
