### ISSUE TITLE
Do images work?

### ISSUE THREAD

**Issue by abitdodgy** [mduvall/grande.js#61]
Are image uploads supported? There reason I ask is because the roadmap says they will eventually be included, but there seems to be some commit that indicates they might have been included: https://github.com/mduvall/grande.js/issues/17

Are there any examples of how to use inline images if they are supported?

**Comment by mduvall** [comment]
Yep pass `allowImages:true` into the constructor.

``` javascript
new Grande(document.querySelectorAll('.foo'), {allowImages:true});
```

**Comment by digitalplaywright** [comment]
When I do that I get the error 

```
Uncaught TypeError: Cannot read property 'children' of undefined 
```

after constructing Grande with

```
grande.bind(document.querySelectorAll("article"));
```

Do you have a tip on how to fix this error?
