### ISSUE TITLE
Emit change events when text is manipulated

### ISSUE THREAD

**Issue by alexslade** [mduvall/grande.js#65]
I.e. when a user emboldens a phrase.

**Comment by mduvall** [comment]
Interesting! A couple of questions, I can get this in soon if you needed.
- What do you envision the API looking like for this?
- Are the events decorated with which toolbar option is highlighted? How will developers distinguish between the different states text could be manipulated?

**Comment by alexslade** [comment]
I don't have a strong suggestion, perhaps just a function passed as an option? Then, on any text change (whether it's just keypress + formatting or something smarter) that gets called.
