### ISSUE TITLE
Any way to change enter press to <br> instead of <p>?

### ISSUE THREAD

**Issue by arkokoley** [mduvall/grande.js#71]
I made a custom dashboard for Wordpress using grande.js. Is there anyway to output line breaks on enter, instead of the regular paragraph break?

**Comment by mduvall** [comment]
@arkokoley Not that I know of now, we are pushing most of the semantic structure to `contenteditable`, it shouldn't be hard to write a wrapper for grande that takes the output and converts paragraphs to line breaks though. If you need help with this, let me know!
