### ISSUE TITLE
Feature request: Test link

### ISSUE THREAD

**Issue by ryanseys** [mduvall/grande.js#72]
Would be great if you could test the link you type. This could be done by detecting holding down Ctrl or Cmd key while you hover the link, making it clickable... or you could add a little button to the link dialog box that you can click to test it.

This link should only open in a new window/tab also, of course. :smile:

**Comment by mduvall** [comment]
@ryanseys Good idea! It is hard to see what the link is when you are editing, currently Medium shows a tooltip for the link - let's do the same.
