### ISSUE TITLE
missing feature

### ISSUE THREAD

**Issue by dyaa** [mduvall/grande.js#9]
it's just missing the image tag

and what about youtube tag and other social media tags like the new wordpress editor

**Comment by mduvall** [comment]
Hi,

The current roadmap is definitely to support `figure` and the `+` button as seen on Medium's site. As for other social media functionality this may be better supported in another library, the goal of this project is to become a drop-in replacement to support the features on Medium's website.

**Comment by meetrichpearson** [comment]
Hi, Are you any closer to adding the ability to include images? I would also love to know if it's possible to use this with a wordpress theme and if so how?
